### ISSUE TITLE
How to prepare input from scRNA-seq raw count matrix to predict cytokine activity in each cells

### ISSUE THREAD

**Issue by niehu2018** [data2intelligence/CytoSig#2]
Is there any examples to show how to prepare input from scRNA-seq raw count matrix?

In the document, you said "For single-cell RNASeq data, we used log2(TPM/10 + 1)".
Then you recommend quantile-normalization across conditions.
And you said "If data is from a sample collection without pairs, please mean-centralize the value of each gene across all samples".
Finally, I am confused about how to prepare input for CytoSig from scRNA-seq raw count matrix.
Please give me some advice!
Thanks

**Comment by data2intelligence** [comment]
Hi, Niehu,
I prepared a command-line tool to prepare CytoSig input from 10x Cell Ranger output: https://github.com/data2intelligence/Tres/blob/master/src/convert_mtx.py

You can see the procedure of all data transformation steps. But in brief summary for you:

If data is a scRNA-Seq raw count matrix, here are steps:

data = data.loc[(data == 0).mean(axis=1) < 1] # remove genes with all zero
data = data.loc[:, data.sum() >= 1000] # remove cells with too few reads

size_factor = 1E5/data.sum() # convert count to TPM/10
data *= size_factor
data = numpy.log2(data + 1)
    
# centralize gene value across all cells
background = data.mean(axis=1) # if you have particular background control cells, such as cells from normal samples, you mean replace the background computation here within control cells.
data = data.subtract(background, axis=0)

**Comment by niehu2018** [comment]
Thanks a lot!
This explanation solved my question.
