### ISSUE TITLE
Interpretation of CytoSig results based on scRNA-seq data

### ISSUE THREAD

**Issue by niehu2018** [data2intelligence/CytoSig#3]
Hi, 
I used scRNA-seq data to compute the cytokine signaling activity with  CytoSig.
I got the z-score and p-value matrix (row by cell, col by cytokine).
Q1: Does the z-score value reflect the signaling activity of cytokines?
Q2: If I want to compare the cytokine activity between two cell types, should I only keep the cells with p-value < 0.05 or 0.01?

Best,
Hu

**Comment by data2intelligence** [comment]
Q1: Yes.
Q2: Please use Benjamini-Hochberg correction first to convert p-value to q-values (FDR). Then use FDR < 0.05.

**Comment by niehu2018** [comment]
Thanks a lot.
This solved my question!

**Comment by SamuelCWJ** [comment]
Hi! Thank you for this really interesting tool! I'm still figuring out how to interpret its results. May I hitch a ride on this question and ask a little more please? I have a few clusters of cells (scRNAseq) that I'm testing this tool on.

1) Regarding the z-score, is it correct for me to say that positive z-scores indicates upregulated signaling activity of cytokines? And negative indicates downregulated activity?

2) Following from 1), would it be correct to say that the coefficient for a positive z-score should be positive too? I.e. upregulated signaling activity in that particular cell for that particular cytokine?

3) After filtering for FDR < 0.05, would it be reasonable to take the average z-score to compare the signaling activity between clusters / cell types?

Thank you so much!

Best Regards,
Samuel
